#!/usr/bin/env bash 
set -xe
cd $GSRC/bin 
rm -f cc 
rm -f  c++ 
rm -f  cpp 
rm -f  g++ 
rm -f  gcc 
rm -f  gdc 
rm -f  gcc-ar 
rm -f  gccgo 
rm -f  gcc-nm 
rm -f  gcc-ranlib 
rm -f  gccrs 
rm -f  gcov 
rm -f  gcov-dump 
rm -f  gcov-tool 
rm -f  gfortran 
rm -f  gm2 
rm -f  gnat 
rm -f  gnatbind 
rm -f  gnatchop 
rm -f  gnatclean 
rm -f  gnatkr 
rm -f  gnatlink 
rm -f  gnatls 
rm -f  gnatmake 
rm -f  gnatname 
rm -f  gnatprep 
rm -f  lto-dump 
rm -f  x86_64-pc-linux-gnu-c++ 
rm -f  x86_64-pc-linux-gnu-g++ 

rm -f  x86_64-pc-linux-gnu-gcc 
rm -f  x86_64-pc-linux-gnu-gcc-ar 
rm -f  x86_64-pc-linux-gnu-gccgo 
rm -f  x86_64-pc-linux-gnu-gcc-nm 
rm -f  x86_64-pc-linux-gnu-gcc-ranlib 
rm -f  x86_64-pc-linux-gnu-gccrs 
rm -f  x86_64-pc-linux-gnu-gfortran 
rm -f  x86_64-pc-linux-gnu-gm2 


ln -s  c++-13                            c++ 
ln -s  cpp-13                            cpp 
ln -s  g++-13                            g++ 
ln -s  gcc-13                            gcc 
ln -s  gdc-13                            gdc 
ln -s  gcc-ar-13                         gcc-ar 
ln -s  gccgo-13                          gccgo 
ln -s  gcc-nm-13                         gcc-nm 
ln -s  gcc-ranlib-13                     gcc-ranlib 
ln -s  gccrs-13                          gccrs 
ln -s  gcov-13                           gcov 
ln -s  gcov-dump-13                      gcov-dump 
ln -s  gcov-tool-13                      gcov-tool 
ln -s  gfortran-13                       gfortran 
ln -s  gm2-13                            gm2 
ln -s  gnat-13                           gnat 
ln -s  gnatbind-13                       gnatbind 
ln -s  gnatchop-13                       gnatchop 
ln -s  gnatclean-13                      gnatclean 
ln -s  gnatkr-13                         gnatkr 
ln -s  gnatlink-13                       gnatlink 
ln -s  gnatls-13                         gnatls 
ln -s  gnatmake-13                       gnatmake 
ln -s  gnatname-13                       gnatname 
ln -s  gnatprep-13                       gnatprep 
ln -s  lto-dump-13                       lto-dump 
ln -s  x86_64-pc-linux-gnu-c++-13        x86_64-pc-linux-gnu-c++ 
ln -s  x86_64-pc-linux-gnu-g++-13        x86_64-pc-linux-gnu-g++ 
#ln -s  x86_64-pc-linux-gnu-gcc-13.0.0    x86_64-pc-linux-gnu-gcc 
ln -s  x86_64-pc-linux-gnu-gcc-13        x86_64-pc-linux-gnu-gcc 
ln -s  x86_64-pc-linux-gnu-gcc-ar-13     x86_64-pc-linux-gnu-gcc-ar 
ln -s  x86_64-pc-linux-gnu-gccgo-13      x86_64-pc-linux-gnu-gccgo 
ln -s  x86_64-pc-linux-gnu-gcc-nm-13     x86_64-pc-linux-gnu-gcc-nm 
ln -s  x86_64-pc-linux-gnu-gcc-ranlib-13 x86_64-pc-linux-gnu-gcc-ranlib 
ln -s  x86_64-pc-linux-gnu-gccrs-13      x86_64-pc-linux-gnu-gccrs 
ln -s  x86_64-pc-linux-gnu-gfortran-13   x86_64-pc-linux-gnu-gfortran 
ln -s  x86_64-pc-linux-gnu-gm2-13        x86_64-pc-linux-gnu-gm2 

ln -s gcc cc


