#!/usr/bin/env bash 
set -xe
cd $GSRC/bin 
rm -f cc 
rm -f  c++ 
rm -f  cpp 
rm -f  g++ 
rm -f  gcc 
rm -f  gdc 
rm -f  gcc-ar 
rm -f  gccgo 
rm -f  gcc-nm 
rm -f  gcc-ranlib 
rm -f  gccrs 
rm -f  gcov 
rm -f  gcov-dump 
rm -f  gcov-tool 
rm -f  gfortran 
rm -f  gm2 
rm -f  gnat 
rm -f  gnatbind 
rm -f  gnatchop 
rm -f  gnatclean 
rm -f  gnatkr 
rm -f  gnatlink 
rm -f  gnatls 
rm -f  gnatmake 
rm -f  gnatname 
rm -f  gnatprep 
rm -f  lto-dump 
rm -f  x86_64-pc-linux-gnu-c++ 
rm -f  x86_64-pc-linux-gnu-g++ 

rm -f  x86_64-pc-linux-gnu-gcc 
rm -f  x86_64-pc-linux-gnu-gcc-ar 
rm -f  x86_64-pc-linux-gnu-gccgo 
rm -f  x86_64-pc-linux-gnu-gcc-nm 
rm -f  x86_64-pc-linux-gnu-gcc-ranlib 
rm -f  x86_64-pc-linux-gnu-gccrs 
rm -f  x86_64-pc-linux-gnu-gfortran 
rm -f  x86_64-pc-linux-gnu-gm2 


ln -s  c++-12                            c++ 
ln -s  cpp-12                            cpp 
ln -s  g++-12                            g++ 
ln -s  gcc-12                            gcc 
ln -s  gdc-12                            gdc 
ln -s  gcc-ar-12                         gcc-ar 
ln -s  gccgo-12                          gccgo 
ln -s  gcc-nm-12                         gcc-nm 
ln -s  gcc-ranlib-12                     gcc-ranlib 
ln -s  gccrs-12                          gccrs 
ln -s  gcov-12                           gcov 
ln -s  gcov-dump-12                      gcov-dump 
ln -s  gcov-tool-12                      gcov-tool 
ln -s  gfortran-12                       gfortran 
ln -s  gm2-12                            gm2 
ln -s  gnat-12                           gnat 
ln -s  gnatbind-12                       gnatbind 
ln -s  gnatchop-12                       gnatchop 
ln -s  gnatclean-12                      gnatclean 
ln -s  gnatkr-12                         gnatkr 
ln -s  gnatlink-12                       gnatlink 
ln -s  gnatls-12                         gnatls 
ln -s  gnatmake-12                       gnatmake 
ln -s  gnatname-12                       gnatname 
ln -s  gnatprep-12                       gnatprep 
ln -s  lto-dump-12                       lto-dump 
ln -s  x86_64-pc-linux-gnu-c++-12        x86_64-pc-linux-gnu-c++ 
ln -s  x86_64-pc-linux-gnu-g++-12        x86_64-pc-linux-gnu-g++ 
#ln -s  x86_64-pc-linux-gnu-gcc-12.0.0    x86_64-pc-linux-gnu-gcc 
ln -s  x86_64-pc-linux-gnu-gcc-12        x86_64-pc-linux-gnu-gcc 
ln -s  x86_64-pc-linux-gnu-gcc-ar-12     x86_64-pc-linux-gnu-gcc-ar 
ln -s  x86_64-pc-linux-gnu-gccgo-12      x86_64-pc-linux-gnu-gccgo 
ln -s  x86_64-pc-linux-gnu-gcc-nm-12     x86_64-pc-linux-gnu-gcc-nm 
ln -s  x86_64-pc-linux-gnu-gcc-ranlib-12 x86_64-pc-linux-gnu-gcc-ranlib 
ln -s  x86_64-pc-linux-gnu-gccrs-12      x86_64-pc-linux-gnu-gccrs 
ln -s  x86_64-pc-linux-gnu-gfortran-12   x86_64-pc-linux-gnu-gfortran 
ln -s  x86_64-pc-linux-gnu-gm2-12        x86_64-pc-linux-gnu-gm2 

ln -s gcc cc



