#!/usr/bin/env bash 
set -xe
cd $GSRC/bin 


rm -f  c++
rm -f  cpp
rm -f  g++
rm -f  gcc
rm -f  gcc-ar
rm -f  gccgo
rm -f  gcc-nm
rm -f  gcc-ranlib
rm -f  gcov
rm -f  gcov-dump
rm -f  gcov-tool
rm -f  gdc
rm -f  gfortran
rm -f  gm2
rm -f  gnat
rm -f  gnatbind
rm -f  gnatchop
rm -f  gnatclean
rm -f  gnatkr
rm -f  gnatlink
rm -f  gnatls
rm -f  gnatmake
rm -f  gnatname
rm -f  gnatprep
rm -f  lto-dump
rm -f  x86_64-pc-linux-gnu-c++
rm -f  x86_64-pc-linux-gnu-g++
rm -f  x86_64-pc-linux-gnu-gcc
rm -f  x86_64-pc-linux-gnu-gcc-ar
rm -f  x86_64-pc-linux-gnu-gccgo
rm -f  x86_64-pc-linux-gnu-gcc-nm
rm -f  x86_64-pc-linux-gnu-gcc-ranlib
rm -f  x86_64-pc-linux-gnu-gccrs
rm -f  x86_64-pc-linux-gnu-gdc
rm -f  x86_64-pc-linux-gnu-gfortran
rm -f  x86_64-pc-linux-gnu-gm2


ln -s  c++-14                                   c++                            
ln -s  cpp-14                                   cpp                            
ln -s  g++-14                                   g++                            
ln -s  gcc-14                                   gcc                            
ln -s  gcc-ar-14                                gcc-ar                         
ln -s  gccgo-14                                 gccgo                          
ln -s  gcc-nm-14                                gcc-nm                         
ln -s  gcc-ranlib-14                            gcc-ranlib                     
ln -s  gcov-14                                  gcov                           
ln -s  gcov-dump-14                             gcov-dump                      
ln -s  gcov-tool-14                             gcov-tool                      
ln -s  gdc-14                                   gdc                            
ln -s  gfortran-14                              gfortran                       
ln -s  gm2-14                                   gm2                            
ln -s  gnat-14                                  gnat                           
ln -s  gnatbind-14                              gnatbind                       
ln -s  gnatchop-14                              gnatchop                       
ln -s  gnatclean-14                             gnatclean                      
ln -s  gnatkr-14                                gnatkr                         
ln -s  gnatlink-14                              gnatlink                       
ln -s  gnatls-14                                gnatls                         
ln -s  gnatmake-14                              gnatmake                       
ln -s  gnatname-14                              gnatname                       
ln -s  gnatprep-14                              gnatprep                       
ln -s  lto-dump-14                              lto-dump                       
ln -s  x86_64-pc-linux-gnu-c++-14               x86_64-pc-linux-gnu-c++        
ln -s  x86_64-pc-linux-gnu-g++-14               x86_64-pc-linux-gnu-g++        
ln -s  x86_64-pc-linux-gnu-gcc-14               x86_64-pc-linux-gnu-gcc        
ln -s  x86_64-pc-linux-gnu-gcc-ar-14            x86_64-pc-linux-gnu-gcc-ar     
ln -s  x86_64-pc-linux-gnu-gccgo-14             x86_64-pc-linux-gnu-gccgo      
ln -s  x86_64-pc-linux-gnu-gcc-nm-14            x86_64-pc-linux-gnu-gcc-nm     
ln -s  x86_64-pc-linux-gnu-gcc-ranlib-14        x86_64-pc-linux-gnu-gcc-ranlib 
ln -s  x86_64-pc-linux-gnu-gccrs-14             x86_64-pc-linux-gnu-gccrs
ln -s  x86_64-pc-linux-gnu-gdc-14               x86_64-pc-linux-gnu-gdc        
ln -s  x86_64-pc-linux-gnu-gfortran-14          x86_64-pc-linux-gnu-gfortran   
ln -s  x86_64-pc-linux-gnu-gm2-14               x86_64-pc-linux-gnu-gm2        
                                          
 













