#!/usr/bin/env bash 

# 12 13 14 15 16 etc 
#
# 16
VERSION=16

set -e

# GSRC is installation prefix
# after installing
cd $GSRC/bin 

a=$(/bin/ls *-$VERSION)
#printf "$a"

for it in  $a ; do
	it2=$(  echo $it |sed   -e "s/-$VERSION//" )
	echo rm -f "$it2" 
	echo ln -s "$it" "$it2"
done

