#!/usr/bin/env bash 

# 12 13 14 15 16 etc 
#
# 16
VERSION=16

set -e

# GSRC is installation prefix after installing

gcclist=$(/bin/ls $GSRC/bin/*-$VERSION)
#printf "$gcclist"


for it in  $gcclist ; do
	echo
	it2=$(  echo $it |sed   -e "s/-$VERSION//" )
	echo rm -f "$it2" 
	echo ln -s "$it" "$it2"
done

