# Copyright © 2013, 2014 Brandon Invergo <brandon@invergo.net>
# Copyright © 2023 Carl Hansen
#
# This file is part of GSRC, the GNU Source Release Collection.
# http://www.gnu.org/software/gsrc
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.


# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org

NAME = Project Center
GARNAME = projectcenter
GARVERSION = 0.7.0
HOME_URL = http://www.gnustep.org/
DESCRIPTION = GNUstep project developer

######################################################################
# https://github.com/gnustep/apps-projectcenter/archive/refs/tags/projectcenter-0_6_2.tar.gz
MASTER_SITES = $(MASTER_GITHUB)
MASTER_SUBDIR = gnustep/apps-projectcenter/archive/refs/tags/
DISTFILES = $(GARNAME)-0_7_0.tar.gz
SIGFILES = 
CONFIGURE_SCRIPTS = 

BUILDDEPS = tools-make libs-base libs-gui libs-back
LIBDEPS =
WORKSRC = $(WORKDIR)/apps-projectcenter-projectcenter-0_7_0
######################################################################

include ../../../gar/gar.lib/gnustep.mk
include config.mk


